/**
 * @file
 *
 * Generated C++ bindings from a SHACL model
 *
 * This file was automatically generated by shacl2code. DO NOT MANUALLY MODIFY IT
 *
 * SPDX-License-Identifier: MIT
 */

#include "util.hpp"

#include <string>

/* */
namespace test_context {
/* */

using std::string_literals::operator""s;

bool isBlankNode(std::string const& id) { return id.rfind("_:", 0) == 0; }

bool isIRI(std::string const& id) {
    if (isBlankNode(id)) {
        return false;
    }

    if (id.find(":") == std::string::npos) {
        return false;
    }

    return true;
}

/* */
}
/* */
