/**
 * @file
 *
 * Generated C++ bindings from a SHACL model
 *
 * This file was automatically generated by shacl2code. DO NOT MANUALLY MODIFY IT
 *
 * SPDX-License-Identifier: MIT
 */

/* */
#ifndef _SHACL2CODE_TEST_API_HPP
#define _SHACL2CODE_TEST_API_HPP

/* */

// clang-format off
// Generic helper definitions for shared library support
#ifndef DOXYGEN_SKIP
#if defined _WIN32 || defined __CYGWIN__
    #define SHACL2CODE_TEST_HELPER_DLL_IMPORT __declspec(dllimport)
    #define SHACL2CODE_TEST_HELPER_DLL_EXPORT __declspec(dllexport)
    #define SHACL2CODE_TEST_HELPER_DLL_LOCAL
#else
    #define SHACL2CODE_TEST_HELPER_DLL_IMPORT __attribute__((visibility("default")))
    #define SHACL2CODE_TEST_HELPER_DLL_EXPORT __attribute__((visibility("default")))
    #define SHACL2CODE_TEST_HELPER_DLL_LOCAL  __attribute__((visibility("hidden")))
#endif

// Now we use the generic helper definitions above to define EXPORT and LOCAL.
// EXPORT is used for the public API symbols. It either DLL imports or DLL
// exports (or does nothing for static build) LOCAL is used for non-api
// symbols.

#ifdef SHACL2CODE_TEST_DLL         // defined if compiled as a DLL
    #ifdef SHACL2CODE_TEST_DLL_EXPORTS // defined if we are building the DLL (instead of using it)
        #define SHACL2CODE_TEST_API SHACL2CODE_TEST_HELPER_DLL_EXPORT
    #else
        #define SHACL2CODE_TEST_API SHACL2CODE_TEST_HELPER_DLL_IMPORT
    #endif  // SHACL2CODE_TEST_DLL_EXPORTS
    #define SHACL2CODE_TEST_LOCAL   SHACL2CODE_TEST_HELPER_DLL_LOCAL
#else  // SHACL2CODE_TEST_DLL is not defined: this means SHACL2CODE_TEST is a static lib.
    #define SHACL2CODE_TEST_API
    #define SHACL2CODE_TEST_LOCAL
#endif  // SHACL2CODE_TEST_DLL
#endif // DOXYGEN_SKIP
// clang-format on

/* */
#endif // _SHACL2CODE_TEST_API_HPP
/* */
