/**
 * @file
 *
 * This file was automatically generated by shacl2code. DO NOT MANUALLY MODIFY IT
 *
 * SPDX-License-Identifier: 0BSD
 */

#include <memory>

#include "object.hpp"
#include "objectpath.hpp"
#include "refproperty.hpp"
#include "walk.hpp"

/* */
namespace test {
/* */

using std::string_literals::operator""s;

void RefPropertyHelper::walkSHACLObject(SHACLObject const* object,
                                        WalkCallback const& callback,
                                        ObjectPath& path) {
    object->walk(callback, path);
}

std::shared_ptr<SHACLObject> RefPropertyHelper::decodeSHACLObject(
    ObjectDecoder& decoder, TypeBase const* type, ErrorHandler& errorHandler,
    ObjectPath& path) {
    return SHACLObject::decode(decoder, type, errorHandler, path);
}

/* */
}
/* */
