//
//
// This file was automatically generated by shacl2code. DO NOT MANUALLY MODIFY IT
//
// SPDX-License-Identifier: MIT

package model

type LinkState struct {
    Objs map[string]SHACLObject
    Missing map[string]bool
}
