//
//
// This file was automatically generated by shacl2code. DO NOT MANUALLY MODIFY IT
//
// SPDX-License-Identifier: MIT

package model

type ErrorHandler interface {
    HandleError(error, Path)
}
