//
//
// This file was automatically generated by shacl2code. DO NOT MANUALLY MODIFY IT
//
// SPDX-License-Identifier: 0BSD

package model

type Optional[T any] struct {
    value *T
}

func (self Optional[T]) Get() T {
    return *self.value
}

func (self Optional[T]) GetDefault(val T) T {
    if ! self.IsSet() {
        return val
    }
    return *self.value
}

func (self Optional[T]) IsSet() bool {
    return self.value != nil
}

func NewOptional[T any](value T) Optional[T] {
    return Optional[T]{&value}
}

func NewEmptyOptional[T any]() Optional[T] {
    return Optional[T]{nil}
}
